spring:
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: my-group
      auto-offset-reset: latest
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      log-container-config: false
